### PR TITLE
Update colobox and jQuery to newer versions

### PR DESCRIPTION
**Pull request by Zen4All**
This change is [Reviewable](https://reviewable.io/reviews/mc12345678/zen-colorbox/3)

### CODE REVIEW

**Comment by mc12345678** [comment]
Installed this into a relatively vanilla install of ZC 1.5.5e, while there is/was also already existing image swap capability, it does/did not directly interfere with the operation of this code.  

I say that to also say, that one thing I noticed which I don't recall being an issue with the older rendition of colorbox is that it seems like the name of the product (provided "below" the image) encroaches on the image itself.. For example, when looking at the demo product 94. On both desktop and mobile half of the image is taken up by the name of the product, mostly because the image is so small... Understandably, it would be desired to provide the "largest" image (for the medium image), but on a user to user basis, it would seem that either a switch should be included or the code be able to "understand" what to do and not cut off the image itself.  Have any ideas or suggestions?

I did find on mobile, that although on zoom, the image "moves" it still is possible to chase the image and it at least end up on the screen.  Seemed that the previous version caused continual chasing never to be onscreen.

All that also possibly gets into the "calls" to the code as part of the settings and I think that the new code should be incorporated (not just the jquery), but seems like should/could be made a smidge better for the general user. :/

**Comment by mc12345678** [comment]
Forgot to mention that was using ZC 1.5.5e classic responsive template for testing. 

Was looking at documentation for colorbox. Wondering if there is enough present to be able to do/use an onComplete event to increase the overall height of the image based on the image height and the height of the title text. Would have to prevent a cyclic loop on an image resize (maybe something like if the height of "window" is greater than image height or set a value that is used in one of the other "notifiers" to prevent further repeat of the process? Huh, or just in the onComplete section evaluate whether to reload/resize.

Haven't found anything specific by Internet search addressing that the title takes up or hides the image. :/

**Comment by Zen4All** [comment]
I ad not noticed the title overlaying the image, because my image are in general large enough. But smaller image do suffer from this issue.
Since the whole box is build by the script, I think the easiest solution may be to change the css. I''l investigate and let you know.

Found this https://github.com/jackmoore/colorbox/issues/556

**Comment by mc12345678** [comment]
While it would be great to add some sort of resize based on this "new" found observation, I'm not so sure that it is worth too much effort to address a really small original picture with a really long name. An alternative may be to hide the title field based on some sort of evaluation, but generally speaking as both you and I commented a bigger picture is usually used and when such is used things are adjusted more sanely. :) 

On another note, I've identified some changes to the base code that would make portions of this plugin more versatile for inclusion in other plugins. Minor changes here and there, but I've been able to incorporate it into attribute images swap with a few changes. Need to see how those affect something like Image Handler to be sure it won't be a problem. This means also that these two should also work with SBA.

**Pull request merged**
